In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay,classification_report,accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import LabelEncoder

In [13]:
dataset = pd.read_csv('Iris.csv')

In [14]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [15]:
dataset.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [20]:
x = dataset.iloc[:,1:5]
y = dataset.iloc[:,5:]

In [21]:
encode = LabelEncoder()
y = encode.fit_transform(y)

/Users/vedantsmac/anaconda3/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [23]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 0)

In [25]:
naive_bayes=GaussianNB()

In [28]:
naive_bayes.fit(x_train,y_train)
pred = naive_bayes.predict(x_test)
print(pred)

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1 1 2 0 2 0 0]


In [29]:
from sklearn.metrics import confusion_matrix

In [30]:
cm = confusion_matrix(y_test,pred)
print(cm)

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


In [31]:
from sklearn.metrics import recall_score,f1_score,accuracy_score,precision_score

In [34]:
accuracy = accuracy_score(y_test,pred)
precision =precision_score(y_test, pred,average='micro')
recall = recall_score(y_test, pred,average='micro')
f1 = f1_score(y_test,pred,average='micro')

print(accuracy)
print(precision)
print(recall)
print(f1)

1.0
1.0
1.0
1.0
